// Inspect Git's index, never unstaged personal work. No model or network calls.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

export function privatePath(path) {
  const p = path.replaceAll('\\', '/').toLowerCase();
  if (/^(?:data|\.forja|\.benchmark)\//.test(p)) return true;
  if (/^docs\/forja\//.test(p) && !['docs/forja/core-conventions.md', 'docs/forja/knowledge.json'].includes(p)) return true;
  if (/^docs\/(?:next-|continuation-|core-benchmark\.|core-validation\.|context-economics\.|github-research\.|knowledge-context\.|benchmarks\/)/.test(p)) return true;
  if (/^tools\/(?:benchmarks\/|audit-|benchmark-core\.|dogfood-)/.test(p)) return true;
  return /(?:^|\/)(?:\.env(?:\..*)?|credentials\.json|.*\.(?:pem|key|keystore|jks)|(?:conversation|transcript|chat-history|sponsor-queue|handover|session-log)(?:[.-].*)?)$/.test(p)
    && !/^test\/[^/]+\.test\.mjs$/.test(p);
}

// Reviewed synthetic regression assets, not captured user conversations.
// Approval is bound to the staged bytes AND finding category. Editing either
// asset requires fresh review; other findings (especially credentials) remain fatal.
const REVIEWED_FIXTURES = {
  'test/fixtures/handover-t3-before.md': {
    sha256: '33682eaf03010a69f481b1b49d1c143f4d365c57d40aae7d946ea01afb6db277',
    reason: 'private execution/research/credential path',
    note: 'Synthetic R-FIXTURE-T3 state generated by test/handover.test.mjs.',
  },
  'test/runner.test.mjs': {
    sha256: 'b963fa7ba7689f2f4eee481b29082f0a2f38bd029434923269e6678a19492ca1',
    reason: 'possible conversation export',
    note: 'Deliberately truncated assistant JSON tests malformed native protocol input.',
  },
};
export function reviewedFixture(path, bytes, reason) {
  const approved = REVIEWED_FIXTURES[path];
  return approved?.reason === reason && createHash('sha256').update(bytes).digest('hex') === approved.sha256
    ? approved.note : null;
}

export function contentFindings(buffer) {
  if (buffer.includes(0)) return []; // Binary assets still need human review.
  const text = buffer.toString('utf8');
  const findings = [];
  if (/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/.test(text)) findings.push('private key');
  if (/\b(?:sk-(?:proj-|ant-)?[A-Za-z0-9_-]{24,}|gh[pousr]_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{30,}|AKIA[A-Z0-9]{16})\b/.test(text)) findings.push('credential-like value');
  if (/(?:[A-Z]:[\\/]Users[\\/][^\s"'`<>]+|\/Users\/[^/\s]+\/|\/home\/[^/\s]+\/)/i.test(text)) findings.push('personal home path');
  if (/\.codex[\\/]attachments[\\/]|"(?:role|type)"\s*:\s*"(?:user|assistant)"\s*,\s*"(?:content|message)"/i.test(text)) findings.push('possible conversation export');
  return findings;
}

export function inspectIndex(root, { tree = false } = {}) {
  const git = args => execFileSync('git', args, { cwd: root, maxBuffer: 32 * 1024 * 1024 });
  const names = git(tree ? ['ls-files', '-z'] : ['diff', '--cached', '--name-only', '--diff-filter=ACMRT', '-z'])
    .toString('utf8').split('\0').filter(Boolean);
  const findings = [];
  const reviewed = [];
  for (const path of names) {
    const bytes = git(['show', `:${path}`]);
    const reasons = [...(privatePath(path) ? ['private execution/research/credential path'] : []), ...contentFindings(bytes)];
    for (const reason of reasons) {
      const note = reviewedFixture(path, bytes, reason);
      if (note) reviewed.push({ path, reason, note });
      else findings.push({ path, reason });
    }
  }
  return { scope: tree ? 'tracked index snapshot; history NOT scanned' : 'staged additions/modifications', files: names.length, findings, reviewed };
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try {
    const result = inspectIndex(process.cwd(), { tree: process.argv.includes('--tree') });
    console.log(JSON.stringify(result, null, 2));
    if (result.findings.length) process.exitCode = 1;
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
